  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: nice-view-battery                
      remote: zuanming                       
      revision: main   
    - name: zmk-oled-adapter
      remote: zuanming
      revision: main
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    # - name: zmk-dongle
    #   remote: zuanming
    #   revision: main
    - name: zmk-dongle-display
      remote: englmaxi
      revision: v0.3
    - name: zmk-config
      remote: zuanming
      revision: main
  self:
    path: config
