# name: build ZMK
# on: [push, pull_request, workflow_dispatch]

# jobs:
#   build:
#     uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

name: Totem ZMK Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Initialize ZMK
      uses: zmkfirmware/zmk-tools@v1
      
    - name: Build Left
      run: west build -s zmk/app -b seeeduino_xiao_ble -d build_left -- -DSHIELD=totem_left_peripheral -DZMK_CONFIG=./config
      
    - name: Build Right
      run: west build -s zmk/app -b seeeduino_xiao_ble -d build_right -- -DSHIELD=totem_right -DZMK_CONFIG=./config
      
    - name: Build Dongle  
      run: west build -s zmk/app -b nice_nano_v2 -d build_dongle -S studio-rpc-usb-uart -- -DSHIELD="totem_dongle dongle_display" -DZMK_CONFIG=./config
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: totem-firmware
        path: |
          build_left/zephyr/zephyr.*
          build_right/zephyr/zephyr.*
          build_dongle/zephyr/zephyr.*
